restaurant/booking/urls.py
from django.urls import path, re_path
from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.menu_list, name = 'menu_list'),
    path('<slug:slug>', views.meal_details, name = 'meal_details'),
]

restaurant/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name = 'home_view'),
]

restaurant/reservation/urls.py
from django.urls import path, re_path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('', views.reserve_table, name = 'reserve_table'),
]

restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')),
    path('booking/', include('booking.urls', namespace='booking')),
    path('reserve_table/', include('reservation.urls', namespace='reservation')),
    path('testimonial/', include('testimonial.urls', namespace='testimonial')),
    path('team/', include('team.urls', namespace= 'team')),
    path('service/', include('service.urls', namespace = 'service')),
    path('about/', include('about.urls', namespace='about')),
    path('contact/', include('contact.urls', namespace = 'contact')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'EpicureResure Administration'                 
admin.site.index_title = 'Features Administration'
admin.site.site_title = "Epicure Admin"

restaurant/team/urls.py
from django.urls import path, re_path
from . import views

app_name = 'team'

urlpatterns = [
    path('', views.team_members, name = 'team_members'),
]

restaurant/home/models.py
from django.db import models

# Create your models here.

restaurant/home/views.py
from django.shortcuts import render
from booking.models import Menu, Category
from service.models import Services
from team.models import Team
from testimonial.models import Testimonial
from reservation.models import reservation
from reservation.forms import ReserveTableForm

# Create your views here.

def home_view(request):
    menu_list = Menu.objects.all()
    categories = Category.objects.all()
    services = Services.objects.all()
    team_members = Team.objects.all()
    testimonial_list = Testimonial.objects.all()
    reserve_form = ReserveTableForm()
    
    if request.method == 'POST':
        reserve_form = ReserveTableForm(request.POST)
        
        if reserve_form.is_valid():
            reserve_form.save()
            
    reserve_form = ReserveTableForm()
    
    context = {
        'menu_list' : menu_list,
        'categories' : categories,
        'services' : services,
        'team_members' : team_members,
        'testimonial_list' : testimonial_list,
        'reserve_form' : reserve_form,
    }
    
    return render(request, 'home/home.html', context)

restaurant/home/templates/home/home.html
{% extends "base.html" %}
{% load static %}
{% block body %}


        <div class="container-xxl position-relative p-0">
            <div class="container-xxl py-5 bg-dark hero-header mb-5">
                <div class="container my-5 py-5">
                    <div class="row align-items-center g-5">
                        <div class="col-lg-6 text-center text-lg-start">
                            <h1 class="display-3 text-white animated slideInLeft">Enjoy Our<br>Delicious Meal</h1>
                            <p class="text-white animated slideInLeft mb-4 pb-2">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                            <a href="{% url 'reservation:reserve_table' %}" class="btn btn-primary py-sm-3 px-sm-5 me-3 animated slideInLeft">Book A Table</a>
                        </div>
                        <div class="col-lg-6 text-center text-lg-end overflow-hidden">
                            <img class="img-fluid" src="{% static 'site_static/img/hero.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Navbar & Hero End -->


        <!-- Service Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h5 class="section-title ff-secondary text-center text-primary fw-normal">Our Services</h5>
                    <h1 class="mb-5">Explore Our Services</h1>
                </div>
                <div class="row g-4">
                    {% for service in services %}
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="service-item rounded pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-user-tie text-primary mb-4"></i>
                                <h5>{{service.name}}</h5>
                                <p>{{service.description}}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Service End -->


        <!-- About Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="row g-5 align-items-center">
                    <div class="col-lg-6">
                        <div class="row g-3">
                            <div class="col-6 text-start">
                                <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.1s" src="{% static 'site_static/img/about-1.jpg' %}">
                            </div>
                            <div class="col-6 text-start">
                                <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.3s" src="{% static 'site_static/img/about-2.jpg' %}" style="margin-top: 25%;">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.5s" src="{% static 'site_static/img/about-3.jpg' %}">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.7s" src="{% static 'site_static/img/about-4.jpg' %}">
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <h5 class="section-title ff-secondary text-start text-primary fw-normal">About Us</h5>
                        <h1 class="mb-4">Welcome to <i class="fa fa-utensils text-primary me-2"></i>Restoran</h1>
                        <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos erat ipsum et lorem et sit, sed stet lorem sit.</p>
                        <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                        <div class="row g-4 mb-4">
                            <div class="col-sm-6">
                                <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                                    <h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">15</h1>
                                    <div class="ps-4">
                                        <p class="mb-0">Years of</p>
                                        <h6 class="text-uppercase mb-0">Experience</h6>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                                    <h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">50</h1>
                                    <div class="ps-4">
                                        <p class="mb-0">Popular</p>
                                        <h6 class="text-uppercase mb-0">Master Chefs</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="btn btn-primary py-3 px-5 mt-2" href="{% url 'team:team_members' %}">Read More</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- About End -->


        <!-- Menu Start -->
        
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h5 class="section-title ff-secondary text-center text-primary fw-normal">Food Menu</h5>
                    <h1 class="mb-5">Most Popular Items</h1>
                </div>
                <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.1s">
                    <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
                        {% for category in categories %}
                            <li class="nav-item">
                                <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3" data-bs-toggle="pill" href="#{{category}}">
                                    <div class="ps-3">
                                        <h6 class="mt-n1 mb-0">{{category}}</h6>
                                    </div>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>


                    
                    <div class="tab-content">
                        {% for category in categories %}
                            <div id="{{category}}" class="tab-pane fade show p-0">
                                <div class="row g-4">

                                    {% for menu in menu_list %}
                                        {% if menu.category == category %}
                                            <div class="col-lg-6">
                                                <div class="d-flex align-items-center">
                                                    <img class="flex-shrink-0 img-fluid rounded" src="{{menu.image.url}}" alt="" style="width: 80px;">
                                                    <div class="w-100 d-flex flex-column text-start ps-4">
                                                        <h5 class="d-flex justify-content-between border-bottom pb-2">
                                                            <span><a href = "{% url 'booking:meal_details' menu.slug %}">{{menu.name}}</a></span>
                                                            <span class="text-primary">{{menu.price}}</span>
                                                
                                                        </h5>
                                                        <small class="fst-italic">{{menu.Description}}</small>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endif %}
                                    {% endfor %}

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Menu End -->


        <!-- Reservation Start -->
        <div class="container-xxl py-5 px-0 wow fadeInUp" data-wow-delay="0.1s">
            <div class="row g-0">
                <div class="col-md-6 bg-dark d-flex align-items-center">
                    <div class="p-5 wow fadeInUp" data-wow-delay="0.2s">
                        <h5 class="section-title ff-secondary text-start text-primary fw-normal">Reservation</h5>
                        <h1 class="text-white mb-4">Book A Table Online</h1>
                    </div>
                </div>

                <div class="col-md-6 d-flex align-items-center">
                    <div class="p-5 wow fadeInUp" data-wow-delay="0.2s">
                        <form action="" method="POST">

                            {% csrf_token %}
                            {{reserve_form}}
                            <p></p>
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">Book Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Reservation Start -->


        <!-- Team Start -->
        
        <div class="container-xxl pt-5 pb-3">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h5 class="section-title ff-secondary text-center text-primary fw-normal">Team Members</h5>
                    <h1 class="mb-5">Our Master Chefs</h1>
                </div>
                <div class="row g-4">
                    {% for team in team_members %}
                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="team-item text-center rounded overflow-hidden">
                            <div class="rounded-circle overflow-hidden m-4">
                                <img class="img-fluid" src="{{team.image.url}}" alt="">
                            </div>
                            <h5 class="mb-0">{{team.name}}</h5>
                            <small>{{team.designation}}</small>
                            <div class="d-flex justify-content-center mt-3">
                                <a class="btn btn-square btn-primary mx-1" href="{{team.facebook}}"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-square btn-primary mx-1" href="{{team.twitter}}"><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-square btn-primary mx-1" href="{{team.insta}}"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Team End -->


        <!-- Testimonial Start -->
        
        <div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
            <div class="container">
                <div class="text-center">
                    <h5 class="section-title ff-secondary text-center text-primary fw-normal">Testimonial</h5>
                    <h1 class="mb-5">Our Clients Say!!!</h1>
                </div>
                <div class="owl-carousel testimonial-carousel">

                    {% for testimonial in testimonial_list %}
                    <div class="testimonial-item bg-transparent border rounded p-4">
                        <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                        <p>{{testimonial.description}}</p>
                        <div class="d-flex align-items-center">
                            <img class="img-fluid flex-shrink-0 rounded-circle" src="{{testimonial.image.url}}" style="width: 50px; height: 50px;">
                            <div class="ps-3">
                                <h5 class="mb-1">{{testimonial.name}}</h5>
                                <small>{{testimonial.profession}}</small>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    
                </div>
            </div>
        </div>
        <!-- Testimonial End -->
        
{% endblock body %}
  