restaurant/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.team_details, name = 'team_details'),
]

restaurant/booking/urls.py
from django.urls import path, re_path
from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.menu_list, name = 'menu_list'),
    path('<slug:slug>', views.meal_details, name = 'meal_details'),
]

restaurant/contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.SpecialRequest, name = 'request_form'),
]

restaurant/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name = 'home_view'),
]

restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')),
    path('booking/', include('booking.urls', namespace='booking')),
    path('reserve_table/', include('reservation.urls', namespace='reservation')),
    path('testimonial/', include('testimonial.urls', namespace='testimonial')),
    path('team/', include('team.urls', namespace= 'team')),
    path('service/', include('service.urls', namespace = 'service')),
    path('about/', include('about.urls', namespace='about')),
    path('contact/', include('contact.urls', namespace = 'contact')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'EpicureResure Administration'                 
admin.site.index_title = 'Features Administration'
admin.site.site_title = "Epicure Admin"

restaurant/team/urls.py
from django.urls import path, re_path
from . import views

app_name = 'team'

urlpatterns = [
    path('', views.team_members, name = 'team_members'),
]

restaurant/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>EpicureReserve: Book Your Table, Select Your Feast</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'site_static/lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'site_static/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'site_static/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'site_static/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'site_static/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Navbar & Hero Start -->
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
                <a href="" class="navbar-brand p-0">
                    <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>EpicureReserve</h1>
                    <!-- <img src="img/logo.png" alt="Logo"> -->
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0 pe-4">
                        <a href="{%url 'home:home_view' %}" class="nav-item nav-link">Home</a>
                        <a href="{%url 'about:team_details' %}" class="nav-item nav-link">About</a>
                        <a href="{% url 'service:services' %}" class="nav-item nav-link">Service</a>
                        <a href="{% url 'booking:menu_list' %}" class="nav-item nav-link">Menu</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu m-0">
                                <a href="{% url 'reservation:reserve_table' %}" class="dropdown-item">Booking</a>
                                <a href="{% url 'team:team_members' %}" class="dropdown-item">Our Team</a>
                                <a href="{% url 'testimonial:testimonial_list' %}" class="dropdown-item">Testimonial</a>
                            </div>
                        </div>
                        <a href="{%url 'contact:request_form' %}" class="nav-item nav-link">Contact</a>
                    </div>
                    <a href="{% url 'reservation:reserve_table' %}" class="btn btn-primary py-2 px-4">Book A Table</a>
                </div>
            </nav>
        </div>


{% block body %}


{% endblock body %}


        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Company</h4>
                        <a class="btn btn-link" href="{%url 'about:team_details' %}">About Us</a>
                        <a class="btn btn-link" href="{%url 'contact:request_form' %}">Contact Us</a>
                        <a class="btn btn-link" href="{% url 'reservation:reserve_table' %}">Reservation</a>
                        <a class="btn btn-link" href="">Privacy Policy</a>
                        <a class="btn btn-link" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Contact</h4>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, Gachibowli, Hyderabad</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+91 9392486859</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>tejudivyateja@gmail.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href="https://x.com/tejudivyateja"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href="https://www.instagram.com/chinnam_divya_teja/?hl=en"><i class="fab fa-instagram"></i></a>
                            <a class="btn btn-outline-light btn-social" href="https://www.youtube.com/@DivyaTeja-nl7oz"><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href="https://www.linkedin.com/in/chinnam-divya-teja-1457851b9/"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Opening</h4>
                        <h5 class="text-light fw-normal">Monday - Saturday</h5>
                        <p>09AM - 09PM</p>
                        <h5 class="text-light fw-normal">Sunday</h5>
                        <p>10AM - 08PM</p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Newsletter</h4>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="{%url 'home:home_view' %}">EpicureReserve</a>, All Right Reserved. 
                            Designed By <a class="border-bottom" href="https://www.linkedin.com/in/chinnam-divya-teja-1457851b9/">Divya Teja</a><br><br>
                            
                        
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="{%url 'home:home_view' %}">Home</a>
                                <a href="">Cookies</a>
                                <a href = "{%url 'contact:request_form' %}">Help</a>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'site_static/lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'site_static/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'site_static/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'site_static/lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'site_static/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'site_static/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'site_static/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'site_static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'site_static/js/main.js' %}"></script>
</body>

</html>